# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='姓名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
    ]
