# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-08 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161108_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_test_case',
            name='id',
            field=models.IntegerField(default=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dict_test_case',
            name='status',
            field=models.IntegerField(blank=True, default=11),
        ),
    ]
