# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_question_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='result_test_runs',
            new_name='result_test_runss',
        ),
    ]
