# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20161110_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('IP_Address', models.TextField()),
                ('Port', models.IntegerField(default=11)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
