# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_create_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_interfacetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.IntegerField(default=11)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('URL', models.TextField()),
                ('contentType', models.TextField()),
                ('param', models.TextField()),
                ('eresults', models.TextField()),
                ('Actualoutput', models.TextField()),
                ('testresult', models.CharField(max_length=64)),
            ],
        ),
    ]
