# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-05 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_create_interfacetest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_interfacetest',
            new_name='createinterfacetest',
        ),
    ]
