# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_use_case_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinterfacetest',
            name='usercaseID',
            field=models.IntegerField(default=11),
        ),
    ]
