# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_createinterfacetest_usercaseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createinterfacetest',
            name='usercaseID',
            field=models.CharField(max_length=255),
        ),
    ]
