# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20161207_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255, verbose_name='项目名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createname', models.CharField(default='anonymous', editable=False, max_length=128, verbose_name='创建者')),
            ],
        ),
    ]
