# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_new_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_item',
            name='itemdescript',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
