# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_new_item_itemdescript'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_item_case_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newitemID', models.CharField(max_length=30, verbose_name='项目ID')),
                ('casesetName', models.CharField(max_length=255, verbose_name='用例集名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createname', models.CharField(default='anonymous', editable=False, max_length=128, verbose_name='创建者')),
                ('casesetdescript', models.TextField(verbose_name='描述')),
            ],
        ),
    ]
