# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_add_item_case_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='uicase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=30, verbose_name='用例集ID')),
                ('Versionnumber', models.CharField(max_length=255, verbose_name='版本编号')),
                ('casename', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('casesetName', models.CharField(max_length=255, verbose_name='所属产品')),
                ('ScriptType', models.CharField(max_length=128, verbose_name='脚本类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Label', models.CharField(max_length=60, verbose_name='标签')),
                ('descript', models.TextField(verbose_name='描述')),
            ],
        ),
    ]
