# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_uicase'),
    ]

    operations = [
        migrations.CreateModel(
            name='casestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.CharField(max_length=30, verbose_name='步骤ID号')),
                ('itemID', models.CharField(max_length=30, verbose_name='用例')),
                ('kword', models.CharField(max_length=255, verbose_name='关键字')),
                ('Roadking', models.CharField(max_length=255, verbose_name='路劲')),
                ('Param', models.TextField(verbose_name='输入参数值')),
                ('Descript', models.TextField(verbose_name='步骤描述')),
            ],
        ),
    ]
